version: '2'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
      MONGO_HOST: mongodb
      PORT: 3000
    ports:
      - 3000:3000